---
# tasks file for hygeia

- name: Install pre-reqs
  yum:
    name: ['java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'gcc-c++', 'make', 'docker', 'python2-pip', 'git']
    state: present
  tags: prereqs

- name: Setup nodejs
  shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -"
  register: result
  tags: prereqs

- debug: var=result
  tags: prereqs

- name: Install nodejs
  yum:
    name: nodejs
    state: present
  tags: prereqs

- name: Download maven
  get_url:
    url: http://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/{{ maven_distro }}-bin.tar.gz 
    dest: /opt
  tags: maven

- name: Expand maven
  shell: cd /opt && tar xzvf /opt/{{ maven_distro }}-bin.tar.gz && mv /opt/{{ maven_distro }} maven
  ignore_errors: true
  tags: maven

- name: Cleanup
  file:
    path: "{{ maven_distro }}-bin.tar.gz"
    state: absent
  tags: maven

- name: Set profile
  copy:
    src: maven.sh
    dest: /etc/profile.d/maven.sh
    mode: ugo+x
  tags: maven

- name: Start Docker
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: docker

- name: pip install python docker sdk
  shell: python -m pip install docker
  register: result
  tags: docker

- debug: var=result
  tags: docker

- name: copy mongo init db script
  copy:
    src: mongo-create-user.js
    dest: /tmp
  tags: mongo

- name: Pull mongodb Docker Image
  docker_container:
    name: mongodb
    image: mongo:4.0.14
    ports: 
      - "27017:27017"
    volumes:
      - /data/db
      - /tmp/mongo-create-user.js:/docker-entrypoint-initdb.d/mongo-create-user.js:ro
    env:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_INITDB_DATABASE: dashboarddb
  tags: mongo

- name: Install Gulp and Bower
  shell: npm install gulp -g && npm install bower -g
  register: npms
  tags: npms

- debug: var=npms
  tags: npms

- name: Git Clone Hygieia API
  git:
    repo: https://github.com/Hygieia/api.git
    dest: /opt/api
  tags: git

- name: Git Clone Hygieia Core
  git:
    repo: https://github.com/Hygieia/hygieia-core.git
    dest: /opt/hygieia-core
  tags: git

- name: Git Clone Hygieia 
  git:
    repo: https://github.com/Hygieia/Hygieia.git
    dest: /opt/Hygieia
  tags: git

- name: Build Hygieia Core
  shell: cd /opt/hygieia-core && /opt/maven/bin/mvn clean install package
  register: result
  tags: build

- debug: var=result
  when: debug
  tags: build


- name: Build Hygieia 
  shell: cd /opt/Hygieia && /opt/maven/bin/mvn clean install package
  register: result
  tags: build

- name: Build Hygieia API
  shell: cd /opt/api && /opt/maven/bin/mvn clean install package
  register: result
  tags: build

- debug: var=result
  tags: build
  when: debug

- name: Create api dashboard properties
  copy:
    src: dashboard.properties
    dest: /opt/api
  tags: props

- name: Copy startup script
  copy:
    src: start-java.sh
    dest: /opt/
    mode: 755
  tags: startup

- name: Copy startup script
  copy:
    src: start-server.sh
    dest: /opt/
    mode: 755
  tags: startup


- name: Start server
  shell: /opt/start-server.sh
  register: result
  tags: startup

- name: Start java
  shell: /opt/start-java.sh
  register: result
  tags: startup


#- name: Start API Server
#  shell: nohup java -jar /opt/api/target/api.jar --spring.config.name=dashboard --spring.config.location=/opt/api/dashboard.properties -Djasypt.encryptor.password=hygieiasecret &
#  tags: startup

#- name: Start Dashboard UI Server
#  shell: 
#    cmd: nohup gulp serve &
#    chdir: /opt/Hygieia/UI/
#  register: result
#  tags: startup2
#
#- debug: var=result
#  tags: startup2
